server:
  port: 3939

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/bfsforum
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mysql
#    url: jdbc:mysql://bfs-forum.cfe6ym4m0t78.us-east-2.rds.amazonaws.com:3306/bfsforum
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: admin
#    password: bfsForum_2025
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
