server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: message-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bfsforum
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: H7z0j41996
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true