spring:
  application:
    name: file-service
  cloud:
    aws:
      region:
        static: us-east-2
s3:
  bucket:
    name: bfs-forum-assets
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
